### PR TITLE
Add support for downloads metadata

### LINKED ISSUE #120: Add support for "downloads" metadata.
Download **counts**, _that is_.

_Personally_, I wouldn't mind if the data was infrequently updated, stale even.

There's plenty of ways to do it.. 

Am happy to put in my 2 cents if the concept is amenable.

### PR DESCRIPTION
**Pull request by gabrielcsapo**
## Description
Add support for "downloads" metadata

## Motivation and Context
fixes #120

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@whmilton @mralexgray what do you guys think?

**Comment by gabrielcsapo** [comment]
going to merge from no response 😞

**Comment by wmhilton** [comment]
Pssh, no need for a sad face! When in doubt, merge! I am juggling a bunch of open source projects and while I do try to catch up on GH issues on weekends, I can't always. So my response time can be like 1~2 weeks. Anyway, I think download counts sound useful!

I did notice you changed one place to using template strings... but now that I'm looking into it support for template strings has been in Node since version 4.0?! So I'm totally cool with that.

**Comment by gabrielcsapo** [comment]
😄 yeah template strings are cool! 

No problem! Just pulling your strings, I am working on the react part of this over the weekend. Excited to keep working on this project!

**Pull request merged**
